
GET http://localhost:3001/api/artists

###

GET http://localhost:3001/api/albums

###

GET http://localhost:3001/api/songs

###

POST http://localhost:3001/api/songs
Content-Type: application/json

{
    "name": "Sample name",
    "imageUrl": "Sample imageUrl",
}